language: php

php:
  - 5.3

before_install:
  - npm install karma

before_script:
  - composer install

script:
  - vendor/bin/phpunit -c application --coverage-text

cache:
  directories:
    - vendor/
