language: php

php:
    - 5.4

before_install:
    - npm install -g casperjs

before_script:
    - mysql -e 'create database workshop_testing_test;'
    - mysql -e 'create database workshop_testing;'
    - echo "USE mysql;\nUPDATE user SET password=PASSWORD('rootslaptazodis') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
    - mysql -u root --password=rootslaptazodis workshop_testing_test < pages.sql
    - mysql -u root --password=rootslaptazodis workshop_testing < pages.sql
    - composer install --prefer-dist
    - php -S localhost:8000 index.php &
    - sleep 3
    - cp application/tests/Functional/Browser/parameters.example.js application/tests/Functional/Browser/parameters.js

script:
    - vendor/bin/phpunit -c application --coverage-text
    - casperjs test application/tests/Functional/Browser/Test

cache:
    directories:
        - vendor/
